export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const AUTH_ERROR = 'AUTH ERROR';
export const USER_FETCHED = 'USER_FETCHED';

export const CLIENTS_SUCCESS = 'CLIENTS_SUCCESS';
export const CLIENTS_FAIL = 'CLIENTS_FAIL';
export const CLIENTS_FETCH_REQUEST = 'CLIENTS_FETCH_REQUEST';

export const CLIENT_PROFILE_SUCCESS = 'CLIENT_PROFILE_SUCCESS';
export const CLIENT_PROFILE_FAIL = 'CLIENT_PROFILE_FAIL';
export const CLIENT_PROFILE_FETCH_REQUEST = 'CLIENT_PROFILE_FETCH_REQUEST';
export const CLIENT_PROFILE_EDIT_SUCCESS = 'CLIENT_PROFILE_EDIT_SUCCESS';
export const CLIENT_PROFILE_EDIT_FAIL = 'CLIENT_PROFILE_EDIT_FAIL';
export const CLIENT_PROFILE_DELETE_SUCCESS = 'CLIENT_PROFILE_DELETE_SUCCESS';
export const CLIENT_PROFILE_DELETE_FAIL = 'CLIENT_PROFILE_DELETE_FAIL';

export const JOBS_SUCCESS = 'JOBS_SUCCESS';
export const JOBS_FAIL = 'JOBS_FAIL';
export const JOBS_FETCH_REQUEST = 'JOBS_FETCH_REQUEST';

export const JOB_SUCCESS = 'JOB_SUCCESS';
export const JOB_FAIL = 'JOB_FAIL';
export const JOB_FETCH_REQUEST = 'JOB_FETCH_REQUEST';

export const JOB_ADD_SUCCESS = 'JOB_ADD_SUCCESS';
export const JOB_ADD_FAIL = 'JOB_ADD_FAIL';

export const JOB_EDIT_SUCCESS = 'JOB_EDIT_SUCCESS';
export const JOB_EDIT_FAIL = 'JOB_EDIT_FAIL';

export const JOB_DELETE_SUCCESS = 'JOB_DELETE_SUCCESS';
export const JOB_DELETE_FAIL = 'JOB_DELETE_FAIL';

export const WORKERS_SUCCESS = 'WORKERS_SUCCESS';
export const WORKERS_FAIL = 'WORKERS_FAIL';
export const WORKERS_FETCH_REQUEST = 'WORKERS_FETCH_REQUEST';

export const WORKER_PROFILE_SUCCESS = 'WORKER_PROFILE_SUCCESS';
export const WORKER_PROFILE_FAIL = 'WORKER_PROFILE_FAIL';
export const WORKER_PROFILE_FETCH_REQUEST = 'WORKER_PROFILE_FETCH_REQUEST';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';